### ISSUE TITLE
genrale question

### ISSUE THREAD

**Issue by gasmia** [WMSPanel/load-balancer#1]
i tried to use your git but it is not working for me the problem is there is no tuto that we can follow it

**Comment by WMSPanel** [comment]
Hello,

Please read this article for more details: http://blog.wmspanel.com/2015/02/hls-dash-media-streaming-load-balancing.html

**Comment by gasmia** [comment]
hi but there is nothing on this article it explain in general how it work, whay you dont explain to me how i can configure this load balancer ?

Envoyé à partir d'Outlookhttp://aka.ms/weboutlook

---

De : Softvelum notifications@github.com
Envoyé : vendredi 4 novembre 2016 03:05
À : WMSPanel/load-balancer
Cc : gasmia; Author
Objet : Re: [WMSPanel/load-balancer] genrale question (#1)

Hello,

Please read this article for more details: http://blog.wmspanel.com/2015/02/hls-dash-media-streaming-load-balancing.html

##

**Comment by WMSPanel** [comment]
This article is the general description of this approach. Please let me know what exactly is not clear in it.

**Comment by gasmia** [comment]
hi,

the artcle explain what i need exactly but there is not demontration for how we can configure it. i need if it is possible a tuto or how to do a live streaming with load balancing

Envoyé à partir d'Outlookhttp://aka.ms/weboutlook

---

De : Softvelum notifications@github.com
Envoyé : vendredi 4 novembre 2016 05:25
À : WMSPanel/load-balancer
Cc : gasmia; Author
Objet : Re: [WMSPanel/load-balancer] genrale question (#1)

This article is the general description of this approach. Please let me know what exactly is not clear in it.

##

**Comment by WMSPanel** [comment]
If you look at test.php you can see example of adding sevarl Nimble instances into the pool and then creating URL according to balancing use case for streams. The last line shows the URLs which you can use for inserting into the player.
