### ISSUE TITLE
Load-balancer base on response time from server?

### ISSUE THREAD

**Issue by ghost** [WMSPanel/load-balancer#2]
Hi WMSPanel team,
It would be perfect if you can add the "least_time" option into load-balancer.
The least outgoing bandwidth or least connections both is both great but not perfect.
Many times one of my server got a fiber cut, although it not gone offline everything is buffering.
Load-balancer still can access that server through API and return server IP to the player.

**Comment by WMSPanel** [comment]
Hi,
Thanks for the feedback, we'll consider that when we get to updating this script.
Feel free to make pull requests for our script if you manage to do that earlier than us.
